services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      # DATABASE_URL: "postgresql://postgres:postgres@db:5432/nest-db"
      DATABASE_URL: "postgresql://postgres:postgres@localhost:5432/mydb?schema=public"
    depends_on:
      - db

  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: mydb
    ports:
      - 5432:5432
    volumes:
      - postgres_mydb:/var/lib/postgresql/mydb

volumes:
  postgres_mydb: